### ISSUE TITLE
NestedField/ObjectField takes too long to index

### ISSUE THREAD

**Issue by juanpsenn** [django-es/django-elasticsearch-dsl#317]
Hello! I'm having serious performance issues when trying to index this model when I add a NestedField or ObjectField to it.
I don't know why, but with 300.000 records the indexing process never ends.
Also I have tried disabling refresh_interval and adding --parallel flag to manage.py search_index --rebuild.

![image](https://user-images.githubusercontent.com/32602005/104499140-64018a80-55bb-11eb-8b63-5ab4e8e67816.png)

Can anyone give me and idea of what can i do?

**Comment by alexgarel** [comment]
Hi @juanpsenn, I can only gives you some clue base on what you say. Maybe the problem is not on the ES side but on the database queryset.

1st verify the fields you use do not provocate a deluge of query by the right use of `select_related` and `prefetch_related` (if you don't know what I'm talking about, go read the doc) in ` get_queryset` on your Document
2nd You must be aware that django cache results in queryset. So iterating over a large queryset might be problematic, it can blow your memory (in the python process side). In this case, you may have to customize the  `_get_actions` method to use iterator() or to empty the cache by using batching.

Hope this helps.

**Comment by juanpsenn** [comment]
Thanks @alexgarel this is what I needed! select_related made the indexing process possible.

**Comment by juanpsenn** [comment]
@alexgarel I think I claimed victory too early... Everything was running great until prefetch_related(). 
Let's suppose I need to index data from these models:

```
class Product(models.Model):
  name = models.CharField(max_length=128)
  brand = models.ForeignKey('Brand', on_delete=models.DO_NOTHING)
  
class Brand(models.Model):
  name = models.CharField(max_length=128)

class Stock(models.Model):
   product = models.ForeignKey('Product', on_delete=models.DO_NOTHING, related_name='brand')
   amount_available = models.IntegerField(default=0)
```

My document looks something like these:

```
class ProductDocument(Document):
   brand = fields.NestedField(properties={
                 'name': fields.TextField()
                 })
   stock = models.ObjectField(properties={
                'amount_available': fields.IntegerField()
                })

   class Index:
         ...
    
   class Django:
        model = Product
        fields = ['name']
        related_models = [Brand, Stock]
        
   def get_instances_from_related(self, related_instance):
        if isinstance(related_instance, Brand):
            return related_instance.product_set.all()
        elif isinstance(related_instance, Stock):
            return related_instance.product
            
    def get_queryset(self):
        return super(ProductDocument, self).get_queryset().select_related(
            'brand'
        ).prefetch_related('stock')
```
The prefetch_related makes it impossible to index +350k Products. I don't know what to do. 
Also checked _get_actions method but didn't know how to deal with it.

**Comment by juanpsenn** [comment]
This solved the problem https://github.com/django-es/django-elasticsearch-dsl/issues/27#issuecomment-612628236 
Anyways I'm facing performance issues since I removed the ```.iterator()``` from ```get_indexing_queryset()```.
